package com.hibernateintegracion.domain;
// Generated 14-dic-2015 18:48:25 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Almacenes generated by hbm2java
 */
@Entity
@Table(name="almacenes")
public class Almacenes implements java.io.Serializable {
	
	@Id
	private int codigo;
	@Column(name="nombres")
	private String nombres;
	@Column(name="direccion")
	private String direccion;
	@Column(name="telefono")
	private String telefono;

	public Almacenes() {
	}

	public Almacenes(int codigo) {
		this.codigo = codigo;
	}

	public Almacenes(int codigo, String nombres, String direccion, String telefono) {
		this.codigo = codigo;
		this.nombres = nombres;
		this.direccion = direccion;
		this.telefono = telefono;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

}
