package com.hibernateintegracion.domain;
// Generated 14-dic-2015 18:48:25 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="pedidos")
public class Pedidos implements java.io.Serializable {

	@Id
	@Column(name="numero", unique=true)
	private int numero;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="codigo_almacen")
	private Almacenes codigo_almacen;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="codigo_cliente")
	private Clientes codigo_cliente;
	
	@Column(name="fecha")
	private String fecha;
	@Column(name="iva")
	private Double iva;
	@Column(name="total")
	private Double total;
	@Column(name="estado")
	private Character estado;

	public Pedidos() {
	}

	public Pedidos(int numero) {
		this.numero = numero;
	}

	public Pedidos(int numero,String fecha, Double iva, Double total,
			Character estado, Almacenes almacenes, Clientes clientes) {
		this.numero = numero;
		this.codigo_almacen = almacenes;
		this.codigo_cliente = clientes;
		this.fecha = fecha;
		this.iva = iva;
		this.total = total;
		this.estado = estado;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public Almacenes getAlmacenes() {
		return this.codigo_almacen;
	}

	public void setAlmacenes(Almacenes almacenes) {
		this.codigo_almacen = almacenes;
	}

	public Clientes getClientes() {
		return this.codigo_cliente;
	}

	public void setClientes(Clientes clientes) {
		this.codigo_cliente = clientes;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public Double getIva() {
		return this.iva;
	}

	public void setIva(Double iva) {
		this.iva = iva;
	}

	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
