package com.hibernateintegracion.domain;
// Generated 14-dic-2015 18:48:25 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */

@Entity
@Table(name="productos")
public class Productos implements java.io.Serializable {

	@Id
	@Column(name="codigo", unique = true)
	private int codigo;
	@Column(name="descripcion")
	private String descripcion;
	@Column(name="stock")
	private Integer stock;
	@Column(name="precio")
	private Double precio;
	
	public Productos() {
	}

	public Productos(int codigo) {
		this.codigo = codigo;
	}

	public Productos(int codigo, String descripcion, Integer stock, Double precio) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.stock = stock;
		this.precio = precio;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

}
